# Generated by Django 5.0.6 on 2024-06-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('breed', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
